// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

#ifndef PROTOBUF_events_2eproto__INCLUDED
#define PROTOBUF_events_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace epf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_events_2eproto();
void protobuf_AssignDesc_events_2eproto();
void protobuf_ShutdownFile_events_2eproto();

class Event;
class Events;

// ===================================================================

class Event : public ::google::protobuf::Message {
 public:
  Event();
  virtual ~Event();

  Event(const Event& from);

  inline Event& operator=(const Event& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Event& default_instance();

  void Swap(Event* other);

  // implements Message ----------------------------------------------

  Event* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Event& from);
  void MergeFrom(const Event& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // optional int32 y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // optional int32 p = 3;
  inline bool has_p() const;
  inline void clear_p();
  static const int kPFieldNumber = 3;
  inline ::google::protobuf::int32 p() const;
  inline void set_p(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:epf.Event)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_p();
  inline void clear_has_p();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  ::google::protobuf::int32 p_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_events_2eproto();
  friend void protobuf_AssignDesc_events_2eproto();
  friend void protobuf_ShutdownFile_events_2eproto();

  void InitAsDefaultInstance();
  static Event* default_instance_;
};
// -------------------------------------------------------------------

class Events : public ::google::protobuf::Message {
 public:
  Events();
  virtual ~Events();

  Events(const Events& from);

  inline Events& operator=(const Events& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Events& default_instance();

  void Swap(Events* other);

  // implements Message ----------------------------------------------

  Events* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Events& from);
  void MergeFrom(const Events& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .epf.Event evt = 1;
  inline int evt_size() const;
  inline void clear_evt();
  static const int kEvtFieldNumber = 1;
  inline const ::epf::Event& evt(int index) const;
  inline ::epf::Event* mutable_evt(int index);
  inline ::epf::Event* add_evt();
  inline const ::google::protobuf::RepeatedPtrField< ::epf::Event >&
      evt() const;
  inline ::google::protobuf::RepeatedPtrField< ::epf::Event >*
      mutable_evt();

  // @@protoc_insertion_point(class_scope:epf.Events)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::epf::Event > evt_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_events_2eproto();
  friend void protobuf_AssignDesc_events_2eproto();
  friend void protobuf_ShutdownFile_events_2eproto();

  void InitAsDefaultInstance();
  static Events* default_instance_;
};
// ===================================================================


// ===================================================================

// Event

// optional int32 x = 1;
inline bool Event::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Event::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Event::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Event::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Event::x() const {
  return x_;
}
inline void Event::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// optional int32 y = 2;
inline bool Event::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Event::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Event::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Event::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Event::y() const {
  return y_;
}
inline void Event::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// optional int32 p = 3;
inline bool Event::has_p() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Event::set_has_p() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Event::clear_has_p() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Event::clear_p() {
  p_ = 0;
  clear_has_p();
}
inline ::google::protobuf::int32 Event::p() const {
  return p_;
}
inline void Event::set_p(::google::protobuf::int32 value) {
  set_has_p();
  p_ = value;
}

// -------------------------------------------------------------------

// Events

// repeated .epf.Event evt = 1;
inline int Events::evt_size() const {
  return evt_.size();
}
inline void Events::clear_evt() {
  evt_.Clear();
}
inline const ::epf::Event& Events::evt(int index) const {
  return evt_.Get(index);
}
inline ::epf::Event* Events::mutable_evt(int index) {
  return evt_.Mutable(index);
}
inline ::epf::Event* Events::add_evt() {
  return evt_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::epf::Event >&
Events::evt() const {
  return evt_;
}
inline ::google::protobuf::RepeatedPtrField< ::epf::Event >*
Events::mutable_evt() {
  return &evt_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace epf

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_events_2eproto__INCLUDED
